<?php

namespace Sistema\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemitovolvoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository {

    public function findAjaxCliente($param) {
        return $this->getEntityManager()
                        ->createQuery('SELECT ti FROM SistemaAdminBundle:Cliente ti
WHERE ti.nombre LIKE \'%' . $param . '%\'')
                        ->getResult();
    }

}
