<?php

namespace Sistema\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemitovolvoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitovolvoRepository extends EntityRepository
{
}
